# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UniSDKDemoForOc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UniSDKDemoForOc
  
  pod 'IQKeyboardManager' #, :path => './../' 安装到Development Pods目录
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'FMDB', '~> 2.7.5'
  pod 'AFNetworking'

  target 'UniSDKDemoForOcTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UniSDKDemoForOcUITests' do
    # Pods for testing
  end

end
